### ISSUE TITLE
Windows 64 build not working

### ISSUE THREAD

**Issue by dfelinto** [dfelinto/virtual_reality_viewport#13]
... and I have no idea why

**Comment by dfelinto** [comment]
Fixed

**Comment by ptabriz** [comment]
So this means that I can go ahead and run the module from the 64 built blender ? Best,Payam 

On Thu, Jun 2, 2016 at 9:05 AM -0700, "Dalai Felinto" notifications@github.com wrote:

Fixed

**Comment by dfelinto** [comment]
Yes, if it does not work please let me know.

**Comment by ptabriz** [comment]
Yeeeey. You blast Dalai. 

On Thu, Jun 2, 2016 at 11:27 AM -0700, "Dalai Felinto" notifications@github.com wrote:

Yes, if it does not work please let me know.
