### ISSUE TITLE
Error toggling to VR mode

### ISSUE THREAD

**Issue by oculushut** [dfelinto/virtual_reality_viewport#2]
Hi there, I get an error when toggling to VR mode.  I am on a Windows 7 64 bit machine running Blender 2.72b.

![](http://i.imgur.com/JxtWK4e.png)

![](http://i.imgur.com/rB5OtYs.png)

Any tips?

Thanks!

Great project btw

**Comment by dfelinto** [comment]
You need a newer Blender. Get the 2.75-testbuild or a recent one from
http://builder.blender.org

**Comment by oculushut** [comment]
Cool.  
- Downloaded 2.75 Test Build from here: http://download.blender.org/release/
- Set DK2 in Extended Mode
- Toggled VR mode on (space and type), ALT+F11, ALT+F10
- Windows + SHIFT + cursor buttons to get to right screen

And then could see what you showed on the YouTube video!

Have done a pull request to add Blender 2.75 prerequisite to README.md.

Thanks!
