### ISSUE TITLE
How to switch render settings?

### ISSUE THREAD

**Issue by InfernoDigital** [dfelinto/virtual_reality_viewport#20]
Ok, so I ordered my Rift just a while ago and was wanting to work on a project in Blender with it. Was wondering if there was a way to change the render setting from solid to rendered for the oculus viewport. Thanks!

**Comment by dfelinto** [comment]
Simple answer is no, rendered mode is not yet supported. Not so simple answer: there is a branch that supports it, but it's really hacky. You can see a preview of the feature here: https://www.youtube.com/watch?v=La3ZaLhvYng

**Comment by InfernoDigital** [comment]
Alright. Thanks for lettin' me know! I'll go check the hack out.
