### ISSUE TITLE
No Module named "Bridge" Error & Error initializing device

### ISSUE THREAD

**Issue by Seymure** [dfelinto/virtual_reality_viewport#24]
Hello
Everytime i try to start the addon i get those error, im using Blender v 2.77 and DK2

**Comment by dfelinto** [comment]
What is your Oculus runtime version?

**Comment by Seymure** [comment]
0.8

**Comment by dfelinto** [comment]
If the latest version doesn't work try the previous one (the one that is
the last to support DK1).

**Comment by Seymure** [comment]
ok, i will try it, thanks for the fast reply and support

**Comment by Seymure** [comment]
i can only use it in debug mode, but i can visualize anything

**Comment by Seymure** [comment]
or if can you tell me the best configuration for the addon, Blender version and Run time, im using windows 7

**Comment by Seymure** [comment]
already found the missing module, everything is working, thx

**Comment by JonKimbel** [comment]
I'm having this same issue with the Rift CV1.  Is the CV1 supported by this addon?

**Comment by dfelinto** [comment]
@JonKimbel CV1 is a separated issue, see #25
